import type { Metadata, Viewport } from "next";
import Header from '../components/Header'
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#778beb",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Header />
        <main>{children}</main>
        <ServiceWorkerRegister /> 
      </body>
    </html>
  );
}
