name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/mds/pwa-project
            rm -rf .next                    # supprime les anciens builds
            git pull origin main
            npm ci                          # installation propre et complète
            npm run build                   # génère le dossier .next/
            pm2 delete mds || true          # supprime l’ancien process s’il existe
            pm2 start npm --name mds -- start