name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/mds/pwa-maxime           # dossier exact de ton projet
            rm -rf .next                      # supprime les anciens builds
            git reset --hard                  # assure toi que les fichiers sont à jour
            git pull origin main              # récupère la dernière version
            npm ci                            # installation propre
            npm run build                     # build Next.js
            pm2 delete next-pwa || true       # supprime l’ancien process
            pm2 start npm --name next-pwa -- start -- -p 40110  # relance sur le bon port
            pm2 save                          # sauvegarde PM2 pour le redémarrage automatique